# api/v1/auth/otp.py
from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends, status

from api import deps
from app.schemas.auth.otp import (
    OTPGenerateRequest,
    OTPVerifyRequest,
    OTPResponse,
    OTPVerifyResponse,
)
from app.services.auth import OTPService

router = APIRouter()


@router.post(
    "/otp/send",
    response_model=OTPResponse,
    status_code=status.HTTP_200_OK,
)
async def send_otp(
    payload: OTPGenerateRequest,
    otp_service: Annotated[OTPService, Depends(deps.get_otp_service)],
) -> OTPResponse:
    """
    Generate an OTP for email/phone/user_id.

    This only stores the OTP; caller is responsible for actually
    sending it via email/SMS using the notification system.
    """
    return otp_service.generate(payload)


@router.post(
    "/otp/verify",
    response_model=OTPVerifyResponse,
    status_code=status.HTTP_200_OK,
)
async def verify_otp(
    payload: OTPVerifyRequest,
    otp_service: Annotated[OTPService, Depends(deps.get_otp_service)],
) -> OTPVerifyResponse:
    """
    Verify an OTP code previously generated by /otp/send.
    """
    return otp_service.verify(payload)